spring:
  aplication:
    name: "Intuit"
  datasource:
    url: jdbc:h2:file:./Intuit/intuitdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


    show-sql: true
    properties:
      hibernate:
        format_sql: true


  h2:
    console:
      enabled: true
      path: /h2-console # Path para acceder a la consola
